error fix
Getting this error for some reason with the query line, fixed with explicit variable:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 test.query('protocol_name == @s1.block_summary["protocol_name"]')

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/frame.py:4440, in DataFrame.query(self, expr, inplace, **kwargs)
   4438 kwargs["level"] = kwargs.pop("level", 0) + 1
   4439 kwargs["target"] = None
-> 4440 res = self.eval(expr, **kwargs)
   4442 try:
   4443     result = self.loc[res]

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/frame.py:4566, in DataFrame.eval(self, expr, inplace, **kwargs)
   4563     kwargs["target"] = self
   4564 kwargs["resolvers"] = tuple(kwargs.get("resolvers", ())) + resolvers
-> 4566 return _eval(expr, inplace=inplace, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/eval.py:336, in eval(expr, parser, engine, local_dict, global_dict, resolvers, level, target, inplace)
    327 # get our (possibly passed-in) scope
    328 env = ensure_scope(
    329     level + 1,
    330     global_dict=global_dict,
   (...)
    333     target=target,
    334 )
--> 336 parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
    338 if engine == "numexpr" and (
    339     is_extension_array_dtype(parsed_expr.terms.return_type)
    340     or getattr(parsed_expr.terms, "operand_types", None) is not None
   (...)
    344     )
    345 ):
    346     warnings.warn(
    347         "Engine has switched to 'python' because numexpr does not support "
    348         "extension array dtypes. Please set your engine to python manually.",
    349         RuntimeWarning,
    350         stacklevel=find_stack_level(),
    351     )

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:809, in Expr.__init__(self, expr, engine, parser, env, level)
    807 self.parser = parser
    808 self._visitor = PARSERS[parser](self.env, self.engine, self.parser)
--> 809 self.terms = self.parse()

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:828, in Expr.parse(self)
    824 def parse(self):
    825     """
    826     Parse an expression.
    827     """
--> 828     return self._visitor.visit(self.expr)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:421, in BaseExprVisitor.visit_Module(self, node, **kwargs)
    419     raise SyntaxError("only a single expression is allowed")
    420 expr = node.body[0]
--> 421 return self.visit(expr, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:424, in BaseExprVisitor.visit_Expr(self, node, **kwargs)
    423 def visit_Expr(self, node, **kwargs):
--> 424     return self.visit(node.value, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:719, in BaseExprVisitor.visit_Compare(self, node, **kwargs)
    717     op = self.translate_In(ops[0])
    718     binop = ast.BinOp(op=op, left=node.left, right=comps[0])
--> 719     return self.visit(binop)
    721 # recursive case: we have a chained comparison, a CMP b CMP c, etc.
    722 left = node.left

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:535, in BaseExprVisitor.visit_BinOp(self, node, **kwargs)
    534 def visit_BinOp(self, node, **kwargs):
--> 535     op, op_class, left, right = self._maybe_transform_eq_ne(node)
    536     left, right = self._maybe_downcast_constants(left, right)
    537     return self._maybe_evaluate_binop(op, op_class, left, right)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:457, in BaseExprVisitor._maybe_transform_eq_ne(self, node, left, right)
    455     left = self.visit(node.left, side="left")
    456 if right is None:
--> 457     right = self.visit(node.right, side="right")
    458 op, op_class, left, right = self._rewrite_membership_op(node, left, right)
    459 return op, op_class, left, right

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:576, in BaseExprVisitor.visit_Subscript(self, node, **kwargs)
    573 def visit_Subscript(self, node, **kwargs):
    574     from pandas import eval as pd_eval
--> 576     value = self.visit(node.value)
    577     slobj = self.visit(node.slice)
    578     result = pd_eval(
    579         slobj, local_dict=self.env, engine=self.engine, parser=self.parser
    580     )

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:415, in BaseExprVisitor.visit(self, node, **kwargs)
    413 method = f"visit_{type(node).__name__}"
    414 visitor = getattr(self, method)
--> 415 return visitor(node, **kwargs)

File ~/opt/anaconda3/envs/mea/lib/python3.8/site-packages/pandas/core/computation/expr.py:646, in BaseExprVisitor.visit_Attribute(self, node, **kwargs)
    644 resolved = self.visit(value).value
    645 try:
--> 646     v = getattr(resolved, attr)
    647     name = self.env.add_tmp(v)
    648     return self.term_type(name, self.env)

AttributeError: 'StimBlock' object has no attribute 'block_summary'